# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard_anal.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'dashboard_anal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61shboard_anal.proto\"|\n\x0f\x41nalysisRequest\x12\x0e\n\x06salary\x18\x01 \x03(\r\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x12\n\nexperience\x18\x03 \x03(\r\x12\x0f\n\x07regions\x18\x04 \x03(\t\x12\x11\n\tcompanies\x18\x05 \x03(\t\x12\x0f\n\x07sources\x18\x06 \x03(\t\"\x99\x01\n\x10\x41nalysisResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x10\n\x08pdf_data\x18\x03 \x01(\x0c\x12\x1e\n\x06images\x18\x04 \x03(\x0b\x32\x0e.AnalysisImage\x12\x1c\n\x05items\x18\x05 \x01(\x0b\x32\r.AnalysisItem\x12\x15\n\x05table\x18\x06 \x03(\x0b\x32\x06.Table\"M\n\rAnalysisImage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x0c\n\x04size\x18\x04 \x01(\x03\"W\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06salary\x18\x02 \x01(\r\x12\x0c\n\x04link\x18\x03 \x01(\t\x12\x12\n\nexperience\x18\x04 \x03(\r\x12\x0e\n\x06region\x18\x05 \x01(\t\"A\n\x0c\x41nalysisItem\x12\x14\n\x0ctotal_number\x18\x01 \x01(\r\x12\x0b\n\x03\x61vg\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\r2I\n\x0f\x41nalysisService\x12\x36\n\x0fGetAnalysisData\x12\x10.AnalysisRequest\x1a\x11.AnalysisResponseB)Z\'pkg/dashboard_anal_pb;dashboard_anal_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_anal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'pkg/dashboard_anal_pb;dashboard_anal_pb'
  _globals['_ANALYSISREQUEST']._serialized_start=24
  _globals['_ANALYSISREQUEST']._serialized_end=148
  _globals['_ANALYSISRESPONSE']._serialized_start=151
  _globals['_ANALYSISRESPONSE']._serialized_end=304
  _globals['_ANALYSISIMAGE']._serialized_start=306
  _globals['_ANALYSISIMAGE']._serialized_end=383
  _globals['_TABLE']._serialized_start=385
  _globals['_TABLE']._serialized_end=472
  _globals['_ANALYSISITEM']._serialized_start=474
  _globals['_ANALYSISITEM']._serialized_end=539
  _globals['_ANALYSISSERVICE']._serialized_start=541
  _globals['_ANALYSISSERVICE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
