// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: dashboard_anal.proto

package dashboard_anal_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос с фильтрами для анализа
type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salary        []uint32               `protobuf:"varint,1,rep,packed,name=salary,proto3" json:"salary,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Experience    []uint32               `protobuf:"varint,3,rep,packed,name=experience,proto3" json:"experience,omitempty"`
	Regions       []string               `protobuf:"bytes,4,rep,name=regions,proto3" json:"regions,omitempty"`
	Companies     []string               `protobuf:"bytes,5,rep,name=companies,proto3" json:"companies,omitempty"`
	Sources       []string               `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_dashboard_anal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_anal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_anal_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetSalary() []uint32 {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *AnalysisRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *AnalysisRequest) GetExperience() []uint32 {
	if x != nil {
		return x.Experience
	}
	return nil
}

func (x *AnalysisRequest) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *AnalysisRequest) GetCompanies() []string {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *AnalysisRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Ответ с данными анализа
type AnalysisResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// PDF файл
	PdfData []byte `protobuf:"bytes,3,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`
	// Картинки аналитики
	Images []*AnalysisImage `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	// Остальные данные
	Items         *AnalysisItem `protobuf:"bytes,5,opt,name=items,proto3" json:"items,omitempty"`
	Table         []*Table      `protobuf:"bytes,6,rep,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_dashboard_anal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_anal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_anal_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalysisResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalysisResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

func (x *AnalysisResponse) GetImages() []*AnalysisImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AnalysisResponse) GetItems() *AnalysisItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AnalysisResponse) GetTable() []*Table {
	if x != nil {
		return x.Table
	}
	return nil
}

type AnalysisImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "chart1.png", "graph2.jpg"
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // сами байты картинки
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                           // размер файла
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisImage) Reset() {
	*x = AnalysisImage{}
	mi := &file_dashboard_anal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisImage) ProtoMessage() {}

func (x *AnalysisImage) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_anal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisImage.ProtoReflect.Descriptor instead.
func (*AnalysisImage) Descriptor() ([]byte, []int) {
	return file_dashboard_anal_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalysisImage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AnalysisImage) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *AnalysisImage) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// таблица вакансий
type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Salary        uint32                 `protobuf:"varint,2,opt,name=salary,proto3" json:"salary,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Experience    uint32                 `protobuf:"varint,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_dashboard_anal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_anal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_dashboard_anal_proto_rawDescGZIP(), []int{3}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetSalary() uint32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Table) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Table) GetExperience() uint32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *Table) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// Отдельный элемент анализа
type AnalysisItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalNumber   uint32                 `protobuf:"varint,1,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	Avg           float32                `protobuf:"fixed32,2,opt,name=avg,proto3" json:"avg,omitempty"`
	Median        uint32                 `protobuf:"varint,3,opt,name=median,proto3" json:"median,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisItem) Reset() {
	*x = AnalysisItem{}
	mi := &file_dashboard_anal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisItem) ProtoMessage() {}

func (x *AnalysisItem) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_anal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisItem.ProtoReflect.Descriptor instead.
func (*AnalysisItem) Descriptor() ([]byte, []int) {
	return file_dashboard_anal_proto_rawDescGZIP(), []int{4}
}

func (x *AnalysisItem) GetTotalNumber() uint32 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *AnalysisItem) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *AnalysisItem) GetMedian() uint32 {
	if x != nil {
		return x.Median
	}
	return 0
}

var File_dashboard_anal_proto protoreflect.FileDescriptor

const file_dashboard_anal_proto_rawDesc = "" +
	"\n" +
	"\x14dashboard_anal.proto\"\xb7\x01\n" +
	"\x0fAnalysisRequest\x12\x16\n" +
	"\x06salary\x18\x01 \x03(\rR\x06salary\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x03(\rR\n" +
	"experience\x12\x18\n" +
	"\aregions\x18\x04 \x03(\tR\aregions\x12\x1c\n" +
	"\tcompanies\x18\x05 \x03(\tR\tcompanies\x12\x18\n" +
	"\asources\x18\x06 \x03(\tR\asources\"\xc8\x01\n" +
	"\x10AnalysisResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bpdf_data\x18\x03 \x01(\fR\apdfData\x12&\n" +
	"\x06images\x18\x04 \x03(\v2\x0e.AnalysisImageR\x06images\x12#\n" +
	"\x05items\x18\x05 \x01(\v2\r.AnalysisItemR\x05items\x12\x1c\n" +
	"\x05table\x18\x06 \x03(\v2\x06.TableR\x05table\"j\n" +
	"\rAnalysisImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x1d\n" +
	"\n" +
	"image_data\x18\x03 \x01(\fR\timageData\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x7f\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06salary\x18\x02 \x01(\rR\x06salary\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1e\n" +
	"\n" +
	"experience\x18\x04 \x01(\rR\n" +
	"experience\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"[\n" +
	"\fAnalysisItem\x12!\n" +
	"\ftotal_number\x18\x01 \x01(\rR\vtotalNumber\x12\x10\n" +
	"\x03avg\x18\x02 \x01(\x02R\x03avg\x12\x16\n" +
	"\x06median\x18\x03 \x01(\rR\x06median2I\n" +
	"\x0fAnalysisService\x126\n" +
	"\x0fGetAnalysisData\x12\x10.AnalysisRequest\x1a\x11.AnalysisResponseB)Z'pkg/dashboard_anal_pb;dashboard_anal_pbb\x06proto3"

var (
	file_dashboard_anal_proto_rawDescOnce sync.Once
	file_dashboard_anal_proto_rawDescData []byte
)

func file_dashboard_anal_proto_rawDescGZIP() []byte {
	file_dashboard_anal_proto_rawDescOnce.Do(func() {
		file_dashboard_anal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_anal_proto_rawDesc), len(file_dashboard_anal_proto_rawDesc)))
	})
	return file_dashboard_anal_proto_rawDescData
}

var file_dashboard_anal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dashboard_anal_proto_goTypes = []any{
	(*AnalysisRequest)(nil),  // 0: AnalysisRequest
	(*AnalysisResponse)(nil), // 1: AnalysisResponse
	(*AnalysisImage)(nil),    // 2: AnalysisImage
	(*Table)(nil),            // 3: Table
	(*AnalysisItem)(nil),     // 4: AnalysisItem
}
var file_dashboard_anal_proto_depIdxs = []int32{
	2, // 0: AnalysisResponse.images:type_name -> AnalysisImage
	4, // 1: AnalysisResponse.items:type_name -> AnalysisItem
	3, // 2: AnalysisResponse.table:type_name -> Table
	0, // 3: AnalysisService.GetAnalysisData:input_type -> AnalysisRequest
	1, // 4: AnalysisService.GetAnalysisData:output_type -> AnalysisResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dashboard_anal_proto_init() }
func file_dashboard_anal_proto_init() {
	if File_dashboard_anal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_anal_proto_rawDesc), len(file_dashboard_anal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_anal_proto_goTypes,
		DependencyIndexes: file_dashboard_anal_proto_depIdxs,
		MessageInfos:      file_dashboard_anal_proto_msgTypes,
	}.Build()
	File_dashboard_anal_proto = out.File
	file_dashboard_anal_proto_goTypes = nil
	file_dashboard_anal_proto_depIdxs = nil
}
